name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer PHP avec cache OPcache pour performances
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, pdo_mysql  # Note: 'mysql' remplacé par 'pdo_mysql'
          coverage: pcov  # Alternative plus rapide à Xdebug
          ini-values: opcache.enable_cli=1  # Activation d'OPcache

      # Étape 3 : Cache des dépendances Composer (DOIT venir avant l'installation)
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Étape 4 : Installation des dépendances
      - name: Install dependencies
        run: |
          composer validate --strict
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # Étape 5 : Exécution des tests avec rapport de couverture
      - name: Run tests and coverage
        run: |
          ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
          ./vendor/bin/phpunit --coverage-html coverage/

      # Étape optionnelle : Upload du rapport de couverture
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
