name: PHPUnit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: pcov  # Alternative plus rapide à Xdebug

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit ^9.0 --no-interaction

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Verify PHPUnit installation
        run: ls -la vendor/bin/phpunit  # Debug step

      - name: Run tests
        run: php vendor/bin/phpunit --coverage-text
