name: PHPUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Configuration PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, pdo_mysql
          coverage: pcov

      # Étape 3: Cache des dépendances
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}

      # Étape 4: Installation des dépendances
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # Étape 5: Exécution des tests
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text

      # Étape 6: Génération du rapport (optionnelle)
      - name: Generate coverage report
        if: success()
        run: ./vendor/bin/phpunit --coverage-html coverage/
